import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import newsRouter from "./news";
import groupsRouter from "./groups";
import problemsRouter from "./problems";
import eventsRouter from "./events";
import usersRouter from "./users";
import mentorRequestsRouter from "./mentorRequests";
import verificationRouter from "./verification";
import teacherFeedbackRouter from "./teacherFeedback";
import jobsRouter from "./jobs";
import announcementsRouter from "./announcements";
import assignmentsRouter from "./assignments";
import studyMaterialsRouter from "./studyMaterials";
import qaRouter from "./qa";
import connectionsRouter from "./connections";
import memoriesRouter from "./memories";
import achievementsRouter from "./achievements";
import clubsRouter from "./clubs";
import studentQueriesRouter from "./studentQueries";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(newsRouter);
router.use(groupsRouter);
router.use(problemsRouter);
router.use(eventsRouter);
router.use(usersRouter);
router.use(mentorRequestsRouter);
router.use(verificationRouter);
router.use(teacherFeedbackRouter);
router.use(jobsRouter);
router.use(announcementsRouter);
router.use(assignmentsRouter);
router.use(studyMaterialsRouter);
router.use(qaRouter);
router.use(connectionsRouter);
router.use(memoriesRouter);
router.use(achievementsRouter);
router.use(clubsRouter);
router.use(studentQueriesRouter);
router.use(reportsRouter);

export default router;
